### PR TITLE
add Java Solution for Problem 242

### PR DESCRIPTION
**Pull request by ashmichheda**

### CODE REVIEW

**Comment by ashmichheda** [comment]
Also, updated readme.md for problem 242

**Comment by ashmichheda** [comment]
Hey @yanglbme , updated the changes. Thanks!

**Comment by yanglbme** [comment]
Hi @ashmichheda 

- use `char[] val1` instead of `char val1[]`
- delete the `import` statement
- use member method instead of static method

**Comment by yanglbme** [comment]
@ashmichheda Merged!

**Pull request merged**
