### PR TITLE
feat: add 2nd ts solution to lc problem: No.2294

### PR DESCRIPTION
**Pull request by rain84**

### CODE REVIEW

**Comment by rain84** [comment]
@yanglbme , hi!

I fixed bug, and now it works.
Please check again. :)

image

**Comment by yanglbme** [comment]
Hi, the time complexity of this solution should be $O(n^2)$. Given that the data size of n for this problem is $10^5$, an $O(n^2) $ solution is likely not acceptable, even though its execution speed is quite fast.

**Comment by rain84** [comment]
> Hi, the time complexity of this solution should be O(n2). Given that the data size of n for this problem is 105, an $O(n^2) $ solution is likely not acceptable, even though its execution speed is quite fast.

Is it worth adding this solution?
How do you think?

**Comment by yanglbme** [comment]
Hello @rain84 

I don't think this solution is worth adding. The complexity of this solution is $O(n^2)$, and if LeetCode increases the intensity of the test cases, it probably won't pass all the test cases.

**Comment by rain84** [comment]
> Hello @rain84
> 
> I don't think this solution is worth adding. The complexity of this solution is O(n2), and if LeetCode increases the intensity of the test cases, it probably won't pass all the test cases.

Hi @yanglbme 
Thanks for your opinion. I guess you are right.
So I close this PR

**Pull request closed without merging**
