### PR TITLE
feat: add python solution to lc problem: No.0590. N-ary Tree Postorde…

### PR DESCRIPTION
**Pull request by AshwinSolanki76**
…r Traversa

### CODE REVIEW

**Comment by yanglbme** [comment]
Hi @AshwinSolanki76 Could you please add the python solution to README.md and README_EN.md files?

**Comment by AshwinSolanki76** [comment]
> Hi @AshwinSolanki76 Could you please add the python solution to README.md and README_EN.md files?

Done ✅

**Comment by yanglbme** [comment]
I think it's better to merge these changes in one commit. @AshwinSolanki76

**Comment by yanglbme** [comment]
1. Fork the repo to your personal GitHub account
2. Clone your repo to your local machine
3. Checkout a new branch, e.g. `git checkout -b lc-solutions`
4. Make some changes
5. Push to your remote GitHub repo
6. Raise up a pull request

**Comment by yanglbme** [comment]
Refer to #514

**Pull request closed without merging**
